### ISSUE TITLE
UI User Friendly Issues

### ISSUE THREAD

**Issue by Baymax-3100** [hmtmcse/dtm#2]
# Showing constant value in:
1. Status
2. Task Type
3. Type

##### Screenshot:
![image](https://user-images.githubusercontent.com/29631226/51797170-42b9ff00-2229-11e9-93f0-1103172478e9.png)

#### Session Problem
New Tab does not get session from parent tab

#### Reload Issue
After Delete page is not reloading correctly

#### Typo Issue
1. Fix typo of remainder to reminder

**Comment by hmtmcse** [comment]
Reminder Spelling mistake Fixed

**Comment by hmtmcse** [comment]
Dear Masum
Thank you for your contribution, your reported above issues are solved.
