### ISSUE TITLE
ToDo Type Changing Issue.

### ISSUE THREAD

**Issue by mahfuzcmt** [hmtmcse/dtm#3]
**Data is gone**
When updating the ToDo type the previous's ToDo type's date is done 👎 

**To Reproduce**
1. Go to ToDoList and Add a new ToDo. 
2. From the list click on early added ToDo and go to Task Actions.
3. Add New Main Action.
4. Click on  a ToDo ( I clicked on "Task" type todo)
5. Change the ToDo type (I changed to "Team Task")
6. Click on the Update button.
7. ToDo is updated.

**Expected behavior**
1. Should take confirmation to make the operation.
2. If possible then should convert the  Main Action's data to new type's related data field(s).

**Screenshots**
![dtm](https://user-images.githubusercontent.com/12166061/51798474-1c9e5a00-223d-11e9-9fac-69d9cd1c1a1f.png)

**Comment by hmtmcse** [comment]
Thanks you so much for your contribution, we are discontinuing the Todo Edit option in this version. **Please don't worry We requested new improvement for more advantage**
Please have look of New feature request: https://github.com/hmtmcse/dtm/issues/10
