### ISSUE TITLE
Session time out 

### ISSUE THREAD

**Issue by ataure** [hmtmcse/dtm#6]
**Describe the feature request**

If session is time out and logout automatically  then when the user log into the DTM again the previous page is not lode. It is start from the home page

**To Reproduce**

1. After log out automatically
2. Then Log in again
3. See home page

**Expected behavior**

It will stay in same page where the user stay previously

**Comment by hmtmcse** [comment]
Thanks for your feedback buddy, hope it will not logout you now, it will prompt login form
